#!/bin/bash
PRE="######################################################
################### COUNTY VIEW ######################
######################################################

window = {
	name = \"holding_view\"
	widgetid = \"holding_view\"
	parentanchor = bottom|left
	allow_outside = yes
	movable = no
	layer = windows_layer
	size = { 625 780 }
"
POST="######################################################
################### COUNTY VIEW ######################
######################################################

window = {
	name = \"holding_view\"
	widgetid = \"holding_view\"
	parentanchor = bottom|left
	allow_outside = yes
	movable = no
	layer = windows_layer
	size = { 625 780 }
	
	#Cfv
	datacontext = \"[HoldingView.GetHolding]\"
	datacontext = \"[HoldingView.GetProvince]\"
	datacontext = \"[HoldingView.GetHolder]\"
	datacontext = \"[Province.GetCounty]\"
	window_local_umbra = {}
	#Cfv end
"